import secrets
from textwrap import dedent

import yaml


_OPER_PASSWORD_HASH = (
    # bcrypt hash of "myorch-local"; not used for remote auth (loopback only)
    "$2a$04$E5GvEZ.O5Os4M.YHBcJYS.4Vu8LRxQp4WQ/WfZxFHM7lI6f.gkxRq"
)


def generate_ergo_config(
    host: str,
    port: int,
    server_name: str = "myorch.local",
) -> str:
    """Return a YAML ergo config string for a loopback IRCv3 server."""

    config = {
        "network": {"name": "myorch"},
        "server": {
            "name": server_name,
            "listeners": {f"{host}:{port}": {}},
            "casemapping": "ascii",
            "enforce-utf8": True,
            "lookup-hostnames": False,
            "enable-rfc3339-time": True,
            "compatibility": {"allow-truncation": False},
            "max-line-len": 8192,
            "ip-cloaking": {"enabled": False},
        },
        "accounts": {
            "registration": {
                "enabled": True,
                "enabled-callbacks": ["none"],
                "verify-timeout": "32h",
            },
            "authentication-enabled": False,
            "multiclient": {
                "enabled": True,
                "allowed-by-default": True,
            },
        },
        "channels": {
            "default-modes": "+nt",
            "max-channels-per-client": 200,
            "registration": {"enabled": True},
        },
        "opers": {
            "claude-bot": {
                "class": "server-admin",
                "whois-line": "is the myorch bridge bot",
                "password": _OPER_PASSWORD_HASH,
            }
        },
        "oper-classes": {
            "server-admin": {
                "title": "Server Admin",
                "capabilities": [
                    "kill",
                    "ban",
                    "oper:local_kill",
                    "oper:local_ban",
                    "oper:local_unban",
                    "rehash",
                    "accreg",
                ],
            }
        },
        "history": {
            "enabled": True,
            "channel-length": 2048,
            "client-length": 1024,
        },
        "datastore": {"path": ""},
        "logging": [
            {
                "method": "stderr",
                "level": "info",
                "type": "* -userinput -useroutput",
            }
        ],
    }
    return yaml.safe_dump(config, sort_keys=False)


def fresh_oper_password() -> str:
    return secrets.token_urlsafe(24)


def _doc_header() -> str:
    return dedent(
        """\
        # Auto-generated by myorch — do not edit manually.
        # Loopback-only IRCv3 server. Regenerate with `myorch setup`.
        """
    )
